- name: Add some objects to the firewall
  hosts: testfw
  connection: local
  gather_facts: False

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks:
  - name: Grab the credentials from ansible-vault
    include_vars: 'firewall-secrets.yml'
    no_log: 'yes'

  - name: Add an address object to the firewall
    panos_object:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      addressobject: 'AD-Server1'
      address: '10.52.247.33'
      address_type: 'ip-netmask'
      tag_name: 'corpaa_ad_server'
      description: 'Application A App server 1'
      operation: 'add'

  - name: Add an address object to the firewall
    panos_object:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      addressobject: 'AD-Server2'
      address: '10.52.247.34'
      address_type: 'ip-netmask'
      tag_name: 'corpaa_ad_server'
      description: 'Application A App server 2'
      operation: 'add'

  - name: Add an address object to the firewall
    panos_object:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      addressobject: 'AD-Server3'
      address: '10.52.247.35'
      address_type: 'ip-netmask'
      tag_name: 'corpaa_ad_server'
      description: 'Application A App server 3'
      operation: 'add'

  - name: Add an address object to the firewall
    panos_object:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      addressobject: 'AD-Server4'
      address: '10.52.247.36'
      address_type: 'ip-netmask'
      tag_name: 'corpaa_ad_server'
      description: 'Application A App server 4'
      operation: 'add'

  - name: Add an address object to the firewall
    panos_object:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      addressobject: 'App-Server1'
      address: '10.52.247.23'
      address_type: 'ip-netmask'
      tag_name: 'dns'
      tag_name: 'ntp'
      tag_name: 'corpaa_ad'
      tag_name: 'duo'
      description: 'Application A App server 1'
      operation: 'add'

  - name: Add an address object to the firewall
    panos_object:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      addressobject: 'App-Server2'
      address: '10.52.247.24'
      address_type: 'ip-netmask'
      tag_name: 'dns'
      tag_name: 'ntp'
      tag_name: 'corpaa_ad'
      tag_name: 'duo'
      description: 'Application A App server 2'
      operation: 'add'

  - name: Add an address object to the firewall
    panos_object:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      addressobject: 'App-Server3'
      address: '10.52.247.25'
      address_type: 'ip-netmask'
      tag_name: 'dns'
      tag_name: 'ntp'
      tag_name: 'corpaa_ad'
      tag_name: 'duo'
      description: 'Application A App server 3'
      operation: 'add'

  - name: Add an address object to the firewall
    panos_object:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      addressobject: 'App-Server4'
      address: '10.52.247.26'
      address_type: 'ip-netmask'
      tag_name: 'dns'
      tag_name: 'ntp'
      tag_name: 'corpaa_ad'
      tag_name: 'duo'
      description: 'Application A App server 4'
      operation: 'add'
