- name: Add some objects to the firewall
  hosts: testfw
  connection: local
  gather_facts: False

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks:
  - name: Grab the credentials from ansible-vault
    include_vars: 'firewall-secrets.yml'
    no_log: 'yes'

  - name: Add an address object to the firewall
    panos_object:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      addressobject: 'AD-Server1'
      address: '10.52.247.33/32'
      address_type: 'ip-netmask'
      tag_name: 'corpaa_ad_server'
      description: 'Application A App server 1'
      operation: 'add'
